In [35]:
import pandas as pd
import numpy as np
import requests

In [3]:
url_periodo1 = 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1/dados?formato=json&dataInicial=01/07/1994&dataFinal=01/07/2004'

In [4]:
url_periodo2 = 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1/dados?formato=json&dataInicial=02/07/2004&dataFinal=01/07/2014'

In [5]:
url_periodo3 = 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1/dados?formato=json&dataInicial=02/07/2014&dataFinal=01/07/2024'

In [6]:
url_periodo4 = 'https://api.bcb.gov.br/dados/serie/bcdata.sgs.1/dados?formato=json&dataInicial=02/07/2024&dataFinal=19/10/2026'

In [7]:
dados1 = requests.get(url_periodo1).json()

In [8]:
dados2 = requests.get(url_periodo2).json()

In [9]:
dados3 = requests.get(url_periodo3).json()

In [10]:
dados4 = requests.get(url_periodo4).json()

In [11]:
df1 = pd.DataFrame(dados1)

In [12]:
df2 = pd.DataFrame(dados2)

In [13]:
df3 = pd.DataFrame(dados3)

In [14]:
df4 = pd.DataFrame(dados4)

In [15]:
df = pd.concat([df1, df2, df3, df4])

In [16]:
df

           data   valor
0    01/07/1994  1.0000
1    04/07/1994  0.9400
2    05/07/1994  0.9320
3    06/07/1994  0.9150
4    07/07/1994  0.9100
..          ...     ...
574  13/10/2026  5.0096
575  14/10/2026  5.0441
576  15/10/2026  5.0521
577  16/10/2026  5.0826
578  19/10/2026  5.0564

[8107 rows x 2 columns]

In [18]:
df.isna().sum()

data     0
valor    0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.duplicated(subset='data').sum()

np.int64(0)

In [21]:
df.reset_index(drop=True)

            data   valor
0     01/07/1994  1.0000
1     04/07/1994  0.9400
2     05/07/1994  0.9320
3     06/07/1994  0.9150
4     07/07/1994  0.9100
...          ...     ...
8102  13/10/2026  5.0096
8103  14/10/2026  5.0441
8104  15/10/2026  5.0521
8105  16/10/2026  5.0826
8106  19/10/2026  5.0564

[8107 rows x 2 columns]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8107 entries, 0 to 578
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    8107 non-null   object
 1   valor   8107 non-null   object
dtypes: object(2)
memory usage: 190.0+ KB

In [26]:
df['data'] = pd.to_datetime(df['data'], format='%d/%m/%Y')

In [27]:
df['valor'] = df['valor'].astype(float)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8107 entries, 0 to 578
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    8107 non-null   datetime64[ns]
 1   valor   8107 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 190.0 KB

In [29]:
df.describe()

                                data        valor
count                           8107  8107.000000
mean   2010-08-27 15:44:25.696312064     2.887374
min              1994-07-01 00:00:00     0.829000
25%              2002-08-06 12:00:00     1.795800
50%              2010-08-27 00:00:00     2.376100
75%              2018-09-20 12:00:00     3.859700
max              2026-10-19 00:00:00     6.208600
std                              NaN     1.460194

In [34]:
csv = df.to_csv('cotacao_dolar_1994_2026.csv', index=False)

In [33]:
df['data'].is_monotonic_increasing

True

In [32]:
df.head()

        data  valor
0 1994-07-01  1.000
1 1994-07-04  0.940
2 1994-07-05  0.932
3 1994-07-06  0.915
4 1994-07-07  0.910